services:
  - type: web
    name: edtech-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://studynotion-five-beta.vercel.app
      - key: PORT
        value: 4000
